CREATE OR REPLACE PACKAGE VBTONLINE_TRANS.MENU AS
TYPE curdatos IS REF CURSOR;
TYPE curdatos1 IS REF CURSOR;
TYPE curdatos2 IS REF CURSOR;



   PROCEDURE LOG_1P (P_CODSIS VARCHAR2, P_CODCIA VARCHAR2, P_LOGIN VARCHAR2, param3 OUT CURDATOS, prespuesta OUT VARCHAR2);
   PROCEDURE INGRE (P_LOGIN VARCHAR2, param3 OUT CURDATOS1, prespuesta OUT VARCHAR2);
   PROCEDURE ENCRIPTA_PW (P_PASS VARCHAR2, param3 OUT CURDATOS2, prespuesta OUT VARCHAR2);

END MENU;
/

